project:
  type: book
  output-dir: docs

book:
  title: "Decision Modeling"
  author: "J. Alejandro Gelves"
  date: "09/22/2023"
  cover-image: cover.png
  chapters:
    - index.qmd
    - Decisions.qmd
    - Tools.qmd
    - Simulation.qmd
    - Tools2.qmd
    - Benchmarks.qmd
    - ETS.qmd
    - ARIMA.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    include-after: custom-tag.html
  pdf:
    documentclass: scrreprt

editor: visual