<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Simulation in R – Decision Modeling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Tools2.html" rel="next">
<link href="./Tools.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2486e1f0a3ee9ee1fc393803a1361cdb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ed6da6eef3892af8a4b5ed59bfb951f5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<!-- Google tag (gtag.js) -->
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-ZBSHZ5F458"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-ZBSHZ5F458');
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Simulation.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Simulation in R</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Decision Modeling</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Decisions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Decisions Under Uncertainty</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Tools for Working With Simulation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Simulation.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Simulation in R</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Tools2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Time Series Tools</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Benchmarks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Model Benchmarks</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ETS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">ETS</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ARIMA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">ARIMA</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#roll-with-it-sushi-needs-your-help" id="toc-roll-with-it-sushi-needs-your-help" class="nav-link active" data-scroll-target="#roll-with-it-sushi-needs-your-help"><span class="header-section-number">3.1</span> Roll With It Sushi Needs Your Help</a></li>
  <li><a href="#model-framework" id="toc-model-framework" class="nav-link" data-scroll-target="#model-framework"><span class="header-section-number">3.2</span> Model Framework</a></li>
  <li><a href="#the-news-vendor-problem" id="toc-the-news-vendor-problem" class="nav-link" data-scroll-target="#the-news-vendor-problem"><span class="header-section-number">3.3</span> The News Vendor Problem</a></li>
  <li><a href="#law-of-large-numbers" id="toc-law-of-large-numbers" class="nav-link" data-scroll-target="#law-of-large-numbers"><span class="header-section-number">3.4</span> Law of Large Numbers</a></li>
  <li><a href="#flaw-of-averages" id="toc-flaw-of-averages" class="nav-link" data-scroll-target="#flaw-of-averages"><span class="header-section-number">3.5</span> Flaw Of Averages</a></li>
  <li><a href="#optimal-order-amount" id="toc-optimal-order-amount" class="nav-link" data-scroll-target="#optimal-order-amount"><span class="header-section-number">3.6</span> Optimal Order Amount</a></li>
  <li><a href="#sensitivity-analysis" id="toc-sensitivity-analysis" class="nav-link" data-scroll-target="#sensitivity-analysis"><span class="header-section-number">3.7</span> Sensitivity Analysis</a></li>
  <li><a href="#readings" id="toc-readings" class="nav-link" data-scroll-target="#readings"><span class="header-section-number">3.8</span> Readings</a></li>
  <li><a href="#lessons-learned-in-this-chapter" id="toc-lessons-learned-in-this-chapter" class="nav-link" data-scroll-target="#lessons-learned-in-this-chapter"><span class="header-section-number">3.9</span> Lessons Learned In This Chapter</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">3.10</span> Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Simulation in R</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In this module we will build our first business simulation model using R. We will start by identifying and defining the parts of the model as this provides the basic structure. We will then iterate our model several times so that we can obtain the distribution of expected outcomes. Finally, we will modify some of the model’s inputs, so that we can check the robustness of our results. Throughout, we will keep every scenario in a single tibble and let R evaluate all of them at once.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(extraDistr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="roll-with-it-sushi-needs-your-help" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="roll-with-it-sushi-needs-your-help"><span class="header-section-number">3.1</span> Roll With It Sushi Needs Your Help</h2>
<p>Renowned for serving the freshest sushi in the city, Roll With It Sushi is hosting a yellow-tail festival. Every morning, the Sous-Chef purchases fish at the market and any unsold fish at the end of the day gets discarded.</p>
<p>The restaurant has contacted you because they are still determining how many people will attend the event and worry about how this will impact their business financially. To ensure they have enough sushi and budget appropriately, they want you to recommend the amount of fish needed. Based on past events, they expect at least 20 people to attend and have the capacity to seat up to 50 guests. They anticipate the most likely attendance to be around 30 people, and without your guidance they feel like this is the best guide in determining the fish needed.</p>
<p>Roll With It Sushi can purchase any quantity of yellow-tail from the fresh market at 9 dollars for 16 ounces (divisible). Each guest at the festival is entitled to 5 ounces of fish. If the sushi runs out, some customers will not be happy. However, the restaurant has promised to refund their entry fee. Additionally, they have promised to serve their famous Miso soup to every attendee. The cost of making a batch for up to 50 guests is 300 dollars.</p>
<p>Given that the festival charges 20 dollars per entry, how much yellow-tail would you recommend the restaurant to purchase to maximize expected profits?</p>
</section>
<section id="model-framework" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="model-framework"><span class="header-section-number">3.2</span> Model Framework</h2>
<p>The restaurant provides you with a lot of information which might be overwhelming at first glance. To make the task less daunting, we should organize/classify the information so that we can create a model. For many business problems, the data can be classified into the following parts:</p>
<ul>
<li><p>The <strong>inputs</strong> have given fixed values and provide the model’s basic structure. These are values that are most likely to be given and determined.</p></li>
<li><p>The <strong>decision variables</strong> are values the decision maker controls. We are usually interested in finding the optimal level of this variable.</p></li>
<li><p>The <strong>calculated values</strong> transform inputs and decision variables to other values that help describe our model. These make the model more informative and often are required to derive outputs.</p></li>
<li><p>The <strong>random variables</strong> are the primary source of uncertainty in the model. They are often modeled by sampling probability distributions.</p></li>
<li><p>The <strong>outputs</strong> are the ultimate values of interest; the inputs, decision variables, random variables, or calculated values determine them.</p></li>
</ul>
<p>Below, you can see how we can classify and input the information in R.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>Order_Oz<span class="ot">&lt;-</span><span class="dv">160</span> <span class="co"># Decision Variable</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>Price_Fish_Oz<span class="ot">&lt;-</span><span class="dv">9</span><span class="sc">/</span><span class="dv">16</span> <span class="co"># Input</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>Price_Miso<span class="ot">&lt;-</span><span class="dv">300</span> <span class="co"># Input</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>Entry_Fee<span class="ot">&lt;-</span><span class="dv">20</span> <span class="co"># Input</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>Fish_Entitled_Oz<span class="ot">&lt;-</span><span class="dv">5</span> <span class="co">#Input</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">20</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>Attendance<span class="ot">&lt;-</span><span class="fu">round</span>(<span class="fu">rtriang</span>(<span class="dv">1</span>,<span class="dv">20</span>,<span class="dv">50</span>,<span class="dv">30</span>),<span class="dv">0</span>) <span class="co"># Random Variable</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>Demand<span class="ot">&lt;-</span>Attendance<span class="sc">*</span>Fish_Entitled_Oz <span class="co"># Calculated</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>Available<span class="ot">&lt;-</span>Order_Oz <span class="co"># Calculated</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>Consumption<span class="ot">&lt;-</span><span class="fu">min</span>(Demand,Available) <span class="co">#Calculated</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>Revenue<span class="ot">&lt;-</span>Consumption<span class="sc">/</span>Fish_Entitled_Oz<span class="sc">*</span>Entry_Fee<span class="co"># Calculated</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>Cost<span class="ot">&lt;-</span>Order_Oz<span class="sc">*</span>Price_Fish_Oz<span class="sc">+</span>Price_Miso <span class="co">#Calculated</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>Profit<span class="ot">&lt;-</span>Revenue<span class="sc">-</span>Cost <span class="co"># Outcome</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the model above, you can see how the inputs have fixed values. These values were given to us by the restaurant and the restaurant has little or no control over them (the market price of the fish, the cost of making Miso soup, etc.). The random variable captures the source of uncertainty (i.e., how many people attend the event). As you can see we have used here the <code>rtriang()</code> function from the <code>extraDistr</code> package to generate the attendance. We have chosen the triangle distribution since the restaurant has provided us with a lower limit (20), an upper limit (50), and a most likely case for attendance (30). Note also the use of the <code>set.seed()</code> function. This allows you to replicate the random numbers generated.</p>
<p>The calculated variables combine inputs, the decision variable, and the random variable to provide insight on how much fish is expected to be both consumed and available. They also help us determine the profit (output), which is our main guide in knowing whether the decision of ordering <span class="math inline">\(x\)</span> ounces of fish is the “best”.</p>
</section>
<section id="the-news-vendor-problem" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="the-news-vendor-problem"><span class="header-section-number">3.3</span> The News Vendor Problem</h2>
<p>Note how the decision variable (Order_Oz) affects directly our outcome (Profit). We can see that it decreases the restaurant’s profit through costs, but also affects revenue through the amount of fish available. This is the heart of the problem. We don’t know how many people will attend, so if the restaurant orders too much fish their profits will go down because their costs are large. However, if they order too little then they will have to issue refunds, which decrease their revenue.</p>
<p>As you observe the <em>Profit</em> formula in the code above, you’ll notice the use of the <code>min()</code> function. This function returns the minimum of the <em>Demand</em> and <em>Available</em> values. The intuition here is that the restaurant can only collect entry fees for people who consumed sushi when the attendance is greater than the amount of sushi available. Likewise, their revenue will be capped at the total amount of people who attended, even if they ordered plenty of fish.</p>
<p>The problem illustrated above is called the news vendor problem. The <strong>news vendor problem</strong> is a classic decision-making problem in operations research and economics that involves deciding how much of a product to order (and sometimes at what price to sell it). The problem is called the “news vendor” problem because it was originally used to model the decision-making process of a newspaper vendor trying to decide how many copies of a newspaper to order and at what price to sell them.</p>
</section>
<section id="law-of-large-numbers" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="law-of-large-numbers"><span class="header-section-number">3.4</span> Law of Large Numbers</h2>
<p>Before we answer the question of how much fish to order, we must realize a couple of flaws of the model we have created. Mainly, we have run the simulation once and it is unlikely (although possible) that the attendance will be exactly the single value simulated by the <code>rtriang()</code> function (<span class="math inline">\(44\)</span>). Instead, we want to provide the restaurant with a set of eventualities. Worst case scenarios (low attendance), best case scenarios (high attendance), and most likely outcome for their decision. This is only possible if we generate several attendance numbers, and see how the profit (output) behaves.</p>
<p>An additional problem is that if we tell the restaurant that the expected profit of ordering <span class="math inline">\(x\)</span> amount of fish is <span class="math inline">\(y\)</span>, we want to make sure that the average is not biased. Recall that as the sample size of a study increases, the average of the sample will converge towards the true population mean. In other words, as the number of simulations in our model increases, the estimate of the expected profit becomes more accurate. This is known as the <strong>Law of Large Numbers</strong>.</p>
<p>The code below repeats the simulation several times, allowing for different attendance scenarios to arise. Although there is not a set number of times one should run a simulation to get a good estimate of the mean (or distribution), computers are powerful enough to run thousands if not millions of simulations. Below we run the simulation 10,000 times for illustration purposes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">10000</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>Sushi<span class="ot">&lt;-</span><span class="fu">tibble</span>(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Attendance=</span><span class="fu">round</span>(<span class="fu">rtriang</span>(n,<span class="dv">20</span>,<span class="dv">50</span>,<span class="dv">30</span>),<span class="dv">0</span>),  <span class="co"># Random Variable</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Demand=</span>Attendance<span class="sc">*</span>Fish_Entitled_Oz,       <span class="co"># Calculated</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Available=</span>Order_Oz,                       <span class="co"># Calculated</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Consumption=</span><span class="fu">pmin</span>(Demand,Available),       <span class="co"># Calculated</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">Revenue=</span>Consumption<span class="sc">/</span>Fish_Entitled_Oz<span class="sc">*</span>Entry_Fee, <span class="co"># Calculated</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">Cost=</span>Order_Oz<span class="sc">*</span>Price_Fish_Oz<span class="sc">+</span>Price_Miso,   <span class="co"># Calculated</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">Profit=</span>Revenue<span class="sc">-</span>Cost)                      <span class="co"># Outcome</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>Sushi</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10,000 × 7
   Attendance Demand Available Consumption Revenue  Cost Profit
        &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
 1         30    150       160         150     600   390    210
 2         35    175       160         160     640   390    250
 3         22    110       160         110     440   390     50
 4         30    150       160         150     600   390    210
 5         20    100       160         100     400   390     10
 6         36    180       160         160     640   390    250
 7         31    155       160         155     620   390    230
 8         30    150       160         150     600   390    210
 9         35    175       160         160     640   390    250
10         29    145       160         145     580   390    190
# ℹ 9,990 more rows</code></pre>
</div>
</div>
<p>The model has not changed at all; only the number of rows has. The <code>tibble()</code> function builds a table one column at a time, and it has two properties that make it ideal for simulation. First, a column may refer to any column defined before it, so the model reads top to bottom exactly like the list of parts above. Second, a single value such as <em>Order_Oz</em> is recycled down the entire column, which is why the inputs and the decision variable do not need to be repeated ten thousand times by hand. Each of the <span class="math inline">\(10{,}000\)</span> rows is now one complete scenario for the festival.</p>
<p>The one change worth highlighting is <code>pmin()</code> in place of <code>min()</code>. The <code>min()</code> function returns a single number, the smallest value it is given, which would collapse our whole column into one value. The <code>pmin()</code> function is the <em>parallel</em> minimum: it compares the vectors element by element and returns a vector of the same length, so each row gets its own minimum of demand and availability. Many R functions come in this pair; <code>pmax()</code> plays the same role for maxima.</p>
<p>We can now summarise the results. The <code>summarise()</code> function collapses a tibble down to the statistics we ask for.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>Sushi <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">Expected_Profit=</span><span class="fu">mean</span>(Profit),</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">SD=</span><span class="fu">sd</span>(Profit),</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                    <span class="at">Worst=</span><span class="fu">min</span>(Profit),</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                    <span class="at">Best=</span><span class="fu">max</span>(Profit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  Expected_Profit    SD Worst  Best
            &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1            211.  56.9    10   250</code></pre>
</div>
</div>
<p>From the simulation it seems like the restaurant would make on average a profit of about <span class="math inline">\(211.5\)</span> dollars if they order <span class="math inline">\(160\)</span> ounces of fish. There are however, a couple of questions left unanswered. First, what are the other possible profits when ordering <span class="math inline">\(160\)</span> ounces? Second, is there another amount of fish that would give them a higher expected profit?</p>
</section>
<section id="flaw-of-averages" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="flaw-of-averages"><span class="header-section-number">3.5</span> Flaw Of Averages</h2>
<p>To answer the first question we can generate a histogram of all the results of our simulation model. We can then report this to the restaurant and make them aware of all of the possible outcomes of ordering <span class="math inline">\(160\)</span> ounces of fish. Below, we show the histogram of our model’s outcomes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>Sushi <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x=</span>Profit), <span class="at">bins=</span><span class="dv">30</span>, <span class="at">fill=</span><span class="st">"grey"</span>, <span class="at">col=</span><span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept=</span><span class="fu">mean</span>(Sushi<span class="sc">$</span>Profit), <span class="at">lwd=</span><span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Expected Profits of an Order of 160 Ounces"</span>,</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">""</span>, <span class="at">y=</span><span class="st">"Frequency"</span>) <span class="sc">+</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Simulation_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The plot is built in layers. The <code>ggplot()</code> function starts an empty canvas from our tibble, <code>geom_histogram()</code> adds the bars, and <code>aes()</code> tells R that the <em>Profit</em> column belongs on the horizontal axis. The <code>geom_vline()</code> layer draws the vertical line at the average, and <code>labs()</code> and <code>theme_classic()</code> control the labels and the overall appearance. Layers are added with <code>+</code>, and each one can be removed or changed without touching the others.</p>
<p>As you can see most of the outcomes are close to <span class="math inline">\(250\)</span> dollars. So a better recommendation to the restaurant would be to inform them that when ordering <span class="math inline">\(160\)</span> ounces, they will most likely get a profit of <span class="math inline">\(250\)</span> dollars. There is a small risk of them making less than <span class="math inline">\(100\)</span> dollars in profit, but they should not expect more than <span class="math inline">\(250\)</span> dollars. The average in this case seems to be a poor predictor of what is expected as its frequency is not very large as shown in the histogram. This result is known as the flaw of averages.</p>
<p><strong>The flaw of averages</strong>, also known as the “law of averages fallacy,” is the idea that the average value of a particular characteristic in a population can be used to represent the value of that characteristic for individual members of the population. This is often not the case because the average value can be misleading and does not take into account the variability and distribution of the characteristic within the population.</p>
</section>
<section id="optimal-order-amount" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="optimal-order-amount"><span class="header-section-number">3.6</span> Optimal Order Amount</h2>
<p>Now to answer the main question, what should be the amount ordered of fish? To answer this question we will substitute several possible order options into our model and then retrieve the one that gives us the highest expected profit.</p>
<p>If you have built this kind of model in a spreadsheet, the natural translation into R is a pair of loops: one that walks through each candidate order, and an inner one that walks through each of the <span class="math inline">\(100{,}000\)</span> scenarios, adding up profit as it goes. A <strong>for loop</strong> repeats a block of code once for each element of a vector. The code below does exactly that, and <code>system.time()</code> records how long it takes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>Order_Options<span class="ot">&lt;-</span><span class="fu">seq</span>(<span class="dv">160</span>,<span class="dv">240</span>,<span class="dv">10</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">100000</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>loop_time<span class="ot">&lt;-</span><span class="fu">system.time</span>({</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set.seed</span>(<span class="dv">12</span>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  Profits<span class="ot">&lt;-</span><span class="fu">numeric</span>(<span class="fu">length</span>(Order_Options))</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  k<span class="ot">&lt;-</span><span class="dv">1</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="cf">for</span> (Order <span class="cf">in</span> Order_Options){</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    total<span class="ot">&lt;-</span><span class="dv">0</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> (j <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n){</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>      Attendance<span class="ot">&lt;-</span><span class="fu">round</span>(<span class="fu">rtriang</span>(<span class="dv">1</span>,<span class="dv">20</span>,<span class="dv">50</span>,<span class="dv">30</span>),<span class="dv">0</span>)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>      total<span class="ot">&lt;-</span>total <span class="sc">+</span> (<span class="fu">min</span>(Attendance<span class="sc">*</span>Fish_Entitled_Oz,Order)<span class="sc">/</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>                        Fish_Entitled_Oz<span class="sc">*</span>Entry_Fee <span class="sc">-</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>                        Order<span class="sc">*</span>Price_Fish_Oz <span class="sc">-</span> Price_Miso)</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>    Profits[k]<span class="ot">&lt;-</span>total<span class="sc">/</span>n</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>    k<span class="ot">&lt;-</span>k<span class="sc">+</span><span class="dv">1</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>})[<span class="st">"elapsed"</span>]</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>loop_time</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>elapsed 
  1.501 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(Profits,<span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 212.04 225.54 234.74 240.56 243.16 242.43 240.51 236.34 231.17</code></pre>
</div>
</div>
<p>The <code>seq()</code> function generates the candidate orders from <span class="math inline">\(160\)</span> to <span class="math inline">\(240\)</span> in steps of <span class="math inline">\(10\)</span>. Everything after that is bookkeeping: an empty vector to hold the answers, a counter <em>k</em> to remember which slot to fill, and a running total that is reset for each order. Nine hundred thousand trips through the inner loop take about 1.5 seconds.</p>
<p>Now consider the same problem the way R prefers to see it. Instead of nine separate simulations, we build <strong>one</strong> tibble with nine hundred thousand rows, where a column records which order that row belongs to. Every calculation is then applied to the whole table at once, and <code>group_by()</code> and <code>summarise()</code> split the results back out by order.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>vector_time<span class="ot">&lt;-</span><span class="fu">system.time</span>({</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set.seed</span>(<span class="dv">12</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  Sushi_Grid<span class="ot">&lt;-</span><span class="fu">tibble</span>(</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Order_Oz=</span><span class="fu">rep</span>(Order_Options, <span class="at">each=</span>n),</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Attendance=</span><span class="fu">round</span>(<span class="fu">rtriang</span>(n<span class="sc">*</span><span class="fu">length</span>(Order_Options),<span class="dv">20</span>,<span class="dv">50</span>,<span class="dv">30</span>),<span class="dv">0</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(<span class="at">Demand=</span>Attendance<span class="sc">*</span>Fish_Entitled_Oz,</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">Consumption=</span><span class="fu">pmin</span>(Demand,Order_Oz),</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">Revenue=</span>Consumption<span class="sc">/</span>Fish_Entitled_Oz<span class="sc">*</span>Entry_Fee,</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>           <span class="at">Cost=</span>Order_Oz<span class="sc">*</span>Price_Fish_Oz<span class="sc">+</span>Price_Miso,</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>           <span class="at">Profit=</span>Revenue<span class="sc">-</span>Cost)</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>  results<span class="ot">&lt;-</span>Sushi_Grid <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Order_Oz) <span class="sc">%&gt;%</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="at">Expected_Profit=</span><span class="fu">mean</span>(Profit))</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>})[<span class="st">"elapsed"</span>]</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>vector_time</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>elapsed 
  0.095 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 2
  Order_Oz Expected_Profit
     &lt;dbl&gt;           &lt;dbl&gt;
1      160            212.
2      170            226.
3      180            235.
4      190            241.
5      200            243.
6      210            242.
7      220            241.
8      230            236.
9      240            231.</code></pre>
</div>
</div>
<p>The vectorized version takes about 0.09 seconds, roughly 16 times faster, and returns the same numbers. Three functions are doing the work. The <code>rep()</code> function with <code>each=n</code> repeats each candidate order <span class="math inline">\(100{,}000\)</span> times in a row, so the first hundred thousand rows are the <span class="math inline">\(160\)</span>-ounce scenario, the next hundred thousand are the <span class="math inline">\(170\)</span>-ounce scenario, and so on. The <code>mutate()</code> function adds the calculated columns, referring to other columns by name. Then <code>group_by(Order_Oz)</code> splits the table into nine groups and <code>summarise()</code> collapses each group into a single row containing its average profit.</p>
<p>There is a second advantage that does not show up on the clock. The loop discarded every scenario as soon as it was added to the running total; all that survived was nine averages. The tibble is still sitting in memory with all nine hundred thousand scenarios in it, so any further question the restaurant asks can be answered without re-running anything.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>Sushi_Grid <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Order_Oz) <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Expected_Profit=</span><span class="fu">mean</span>(Profit),</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">Worst_Case=</span><span class="fu">quantile</span>(Profit,<span class="fl">0.05</span>),</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">Best_Case=</span><span class="fu">quantile</span>(Profit,<span class="fl">0.95</span>),</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">Chance_Of_Loss=</span><span class="fu">mean</span>(Profit<span class="sc">&lt;</span><span class="dv">0</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 9 × 5
  Order_Oz Expected_Profit Worst_Case Best_Case Chance_Of_Loss
     &lt;dbl&gt;           &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;          &lt;dbl&gt;
1      160            212.       90        250         0      
2      170            226.       84.4      284.        0      
3      180            235.       78.8      319.        0.00064
4      190            241.       73.1      353.        0.00094
5      200            243.       67.5      388.        0.0009 
6      210            242.       61.9      422.        0.00089
7      220            241.       56.2      456.        0.00745
8      230            236.       50.6      451.        0.00755
9      240            231.       45        465         0.0071 </code></pre>
</div>
</div>
<p>A picture makes the comparison easier to communicate. The <code>geom_line()</code> and <code>geom_point()</code> layers draw the expected profit at each candidate order.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>results <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Order_Oz,<span class="at">y=</span>Expected_Profit)) <span class="sc">+</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Expected Profit by Order Quantity"</span>,</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"Ounces Ordered"</span>, <span class="at">y=</span><span class="st">"Expected Profit"</span>) <span class="sc">+</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Simulation_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This table suggests that ordering <span class="math inline">\(160\)</span> ounces is not optimal, once again highlighting that the average attendance is not a good estimate of how much fish we should order. Instead, we can see that <span class="math inline">\(200\)</span> ounces of fish should be ordered (this feeds <span class="math inline">\(40\)</span> people) to maximize the expected profits (<span class="math inline">\(243.16\)</span> dollars). Rather than reading the answer off the table by eye, we can ask for it directly with <code>slice_max()</code>, which keeps the row with the largest value of the column we name.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>results <span class="sc">%&gt;%</span> <span class="fu">slice_max</span>(Expected_Profit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  Order_Oz Expected_Profit
     &lt;dbl&gt;           &lt;dbl&gt;
1      200            243.</code></pre>
</div>
</div>
<p>One word of caution about the grid approach: it holds every scenario in memory at once. Nine hundred thousand rows is nothing for a modern laptop, but if you were comparing a thousand order quantities you might prefer to simulate one order at a time and keep only the summary. The <code>map_dbl()</code> function from the tidyverse does this without the bookkeeping a loop requires. It applies a function to each element of a vector and returns a numeric vector of results.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">map_dbl</span>(Order_Options, <span class="cf">function</span>(Order){</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  Attendance<span class="ot">&lt;-</span><span class="fu">round</span>(<span class="fu">rtriang</span>(n,<span class="dv">20</span>,<span class="dv">50</span>,<span class="dv">30</span>),<span class="dv">0</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mean</span>(<span class="fu">pmin</span>(Attendance<span class="sc">*</span>Fish_Entitled_Oz,Order)<span class="sc">/</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>         Fish_Entitled_Oz<span class="sc">*</span>Entry_Fee <span class="sc">-</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>         Order<span class="sc">*</span>Price_Fish_Oz <span class="sc">-</span> Price_Miso)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>})</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 212.0358 225.5356 234.7398 240.5558 243.1574 242.4270 240.5060 236.3400
[9] 231.1714</code></pre>
</div>
</div>
<p>Notice that the body of the function is still fully vectorized; <code>map_dbl()</code> is only replacing the outer loop over the nine candidate orders. That is the general rule. Vectorize the part of the model that runs many times, and use the map family for the handful of cases that genuinely have to be handled one at a time.</p>
</section>
<section id="sensitivity-analysis" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="sensitivity-analysis"><span class="header-section-number">3.7</span> Sensitivity Analysis</h2>
<p>What if the price of yellow-tail increases unexpectedly? What if the restaurant wishes to provide each guest with six ounces of fish instead of five? The model we have created above can accommodate these changes easily by just changing the input values. We can additionally inform the restaurant how sensitive the results are to changes in key inputs or assumptions. This is the idea behind sensitivity analysis.</p>
<p><strong>Sensitivity analysis</strong> assesses the robustness of a model or decision by evaluating the impact of changes in certain key input variables on the output of the model or decision. Sensitivity analysis helps to identify which variables are most important and how sensitive the output is to changes in those variables.</p>
<p>Let’s consider providing each guest with five, six, or seven ounces of fish. Because our model is already a table of scenarios, adding a second dimension is a matter of making the table bigger. The <code>expand_grid()</code> function creates every combination of the values it is given, which is exactly the set of scenarios we need: three serving sizes, times eighteen candidate orders, times fifty thousand replications.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>n<span class="ot">&lt;-</span><span class="dv">50000</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>Fish_Options<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">7</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>Order_Options<span class="ot">&lt;-</span><span class="fu">seq</span>(<span class="dv">150</span>,<span class="dv">320</span>,<span class="dv">10</span>)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12</span>)</span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>Sensitivity<span class="ot">&lt;-</span><span class="fu">expand_grid</span>(<span class="at">Fish_Entitled_Oz=</span>Fish_Options,</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>                         <span class="at">Order_Oz=</span>Order_Options,</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>                         <span class="at">Replication=</span><span class="dv">1</span><span class="sc">:</span>n) <span class="sc">%&gt;%</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Attendance=</span><span class="fu">round</span>(<span class="fu">rtriang</span>(<span class="fu">n</span>(),<span class="dv">20</span>,<span class="dv">50</span>,<span class="dv">30</span>),<span class="dv">0</span>),</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">Demand=</span>Attendance<span class="sc">*</span>Fish_Entitled_Oz,</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">Consumption=</span><span class="fu">pmin</span>(Demand,Order_Oz),</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">Profit=</span>Consumption<span class="sc">/</span>Fish_Entitled_Oz<span class="sc">*</span>Entry_Fee <span class="sc">-</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>           Order_Oz<span class="sc">*</span>Price_Fish_Oz <span class="sc">-</span> Price_Miso)</span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>Sensitivity_Results<span class="ot">&lt;-</span>Sensitivity <span class="sc">%&gt;%</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Fish_Entitled_Oz,Order_Oz) <span class="sc">%&gt;%</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Expected_Profit=</span><span class="fu">mean</span>(Profit), <span class="at">.groups=</span><span class="st">"drop"</span>)</span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>(Best<span class="ot">&lt;-</span>Sensitivity_Results <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Fish_Entitled_Oz) <span class="sc">%&gt;%</span></span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a>    <span class="fu">slice_max</span>(Expected_Profit))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
# Groups:   Fish_Entitled_Oz [3]
  Fish_Entitled_Oz Order_Oz Expected_Profit
             &lt;dbl&gt;    &lt;dbl&gt;           &lt;dbl&gt;
1                5      200            242.
2                6      240            221.
3                7      280            198.</code></pre>
</div>
</div>
<p>The <code>n()</code> function returns the number of rows in the tibble, so a single call to <code>rtriang()</code> fills all 2,700,000 scenarios with attendance draws. The <code>.groups="drop"</code> argument simply tells <code>summarise()</code> to hand back an ordinary ungrouped tibble, and <code>slice_max()</code> is applied within each serving size to return the best order quantity for each.</p>
<p>When each guest gets six ounces of fish, the restaurant should order <span class="math inline">\(240\)</span> ounces, yielding an expected profit of <span class="math inline">\(221\)</span> dollars. When each guest gets seven ounces, the restaurant should order <span class="math inline">\(280\)</span> ounces, which generates an expected profit of <span class="math inline">\(198\)</span> dollars. Perhaps providing each guest with more fish is a bad idea, as profits are highly sensitive to every ounce increase.</p>
<p>Plotting all three curves at once makes the point to a non-technical audience in a single image. Mapping the serving size to <code>col</code> inside <code>aes()</code> draws one line per group and adds a legend automatically.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>Sensitivity_Results <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Order_Oz, <span class="at">y=</span>Expected_Profit,</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">col=</span><span class="fu">factor</span>(Fish_Entitled_Oz))) <span class="sc">+</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Sensitivity of Expected Profit to the Serving Size"</span>,</span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"Ounces Ordered"</span>, <span class="at">y=</span><span class="st">"Expected Profit"</span>,</span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="st">"Ounces per Guest"</span>) <span class="sc">+</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Simulation_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Notice how flat each curve is near its peak. The restaurant loses very little by ordering ten or twenty ounces on either side of the optimum, which is worth telling them: the recommendation is robust, and they do not need to hit the number exactly.</p>
</section>
<section id="readings" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="readings"><span class="header-section-number">3.8</span> Readings</h2>
<p>The readings for this chapter will introduce the application of simulation models to business. <span class="citation" data-cites="PMS">Winston and Albright (<a href="references.html#ref-PMS" role="doc-biblioref">2019</a>)</span> highlight the technical application of the models using Excel. It is recommended that you follow in R instead. <span class="citation" data-cites="KI">Kwak and Ingall (<a href="references.html#ref-KI" role="doc-biblioref">2007</a>)</span> motivates the use of Monte Carlo simulation for managing project risks and uncertainties.</p>
<ul>
<li><p><span class="citation" data-cites="PMS">Winston and Albright (<a href="references.html#ref-PMS" role="doc-biblioref">2019</a>)</span> Chapter 10.3 (Simulation and the Flaw of Averages), and 10.4 (Simulation with Built-In Excel Tools). Example 10.4 (Additional Uncertainty at Walton Bookstore) It is recommended you follow along using R instead of Excel.</p></li>
<li><p><span class="citation" data-cites="KI">Kwak and Ingall (<a href="references.html#ref-KI" role="doc-biblioref">2007</a>)</span></p></li>
</ul>
</section>
<section id="lessons-learned-in-this-chapter" class="level2" data-number="3.9">
<h2 data-number="3.9" class="anchored" data-anchor-id="lessons-learned-in-this-chapter"><span class="header-section-number">3.9</span> Lessons Learned In This Chapter</h2>
<ul>
<li><p>Identify the parts of a simulation model.</p></li>
<li><p>Create a simulation model in R by storing every scenario in a tibble.</p></li>
<li><p>Identify the Flaw of Averages.</p></li>
<li><p>Find optimal values in simulation models with <code>group_by()</code> and <code>summarise()</code>.</p></li>
<li><p>Run a sensitivity analysis over several inputs at once with <code>expand_grid()</code>.</p></li>
</ul>
</section>
<section id="exercises" class="level2" data-number="3.10">
<h2 data-number="3.10" class="anchored" data-anchor-id="exercises"><span class="header-section-number">3.10</span> Exercises</h2>
<ol type="1">
<li><p>Apple is preparing to launch a special edition smartphone accessory designed exclusively for its latest iPhone. This accessory is only compatible with this specific model, and the company anticipates that demand will peak during the first 12 months following the smartphone’s release. After this period, a new model of the smartphone is expected to be released, rendering the accessory obsolete. The company estimates that demand for the accessory during the twelve-month period is governed by the probability distribution in the table below.</p>
<p>The production involves a fixed cost of 20,000 dollars, with a variable cost of 15 dollars per unit produced. Each accessory is sold for 100 dollars. However, any unsold units after the twelve-month period will have no value, as they are not compatible with the newest iPhone.</p>
<p>The company is considering producing 10,000 units of the accessory. Using a simulation with 100,000 replications, calculate the expected profit and standard deviation. Additionally, determine the range within which the company can be 90% certain that the actual profit from selling the accessory during the twelve-month period will fall. Build the simulation as a single tibble and use <code>sample()</code> with the <em>prob</em> argument to draw the demands.</p></li>
</ol>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Demand (units)</th>
<th style="text-align: center;">Probability (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">6,000</td>
<td style="text-align: center;">10%</td>
</tr>
<tr class="even">
<td style="text-align: center;">7,000</td>
<td style="text-align: center;">20%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">8,000</td>
<td style="text-align: center;">30%</td>
</tr>
<tr class="even">
<td style="text-align: center;">9,000</td>
<td style="text-align: center;">25%</td>
</tr>
<tr class="odd">
<td style="text-align: center;">10,000</td>
<td style="text-align: center;">15%</td>
</tr>
</tbody>
</table>
<details>
<summary>
Suggested Answer
</summary>
<p><em>Expected Profit: 645,000</em></p>
<p><em>Standard Deviation: 119,326</em></p>
<p><em>90% Confidence Interval: [430,000, 830,000]</em></p>
</details>
<ol start="2" type="1">
<li><p>Alaska Airlines is preparing for the peak holiday travel season and needs to decide how many seats to overbook on the SEA-SFO route. Overbooking is expected in the airline industry, as some passengers typically do not show up for their flights. The airline has data indicating that the number of no-show passengers on this route follows a normal distribution with a mean of 20 and a standard deviation of 5.</p>
<p>If the airline does not overbook enough seats, empty seats result in lost revenue, as the cost of an unused seat is estimated to be $300. However, if the airline overbooks too many seats, it may need to compensate bumped passengers with vouchers worth $600 each. Use 10,000 simulations to determine the optimal number of seats to overbook to minimize the airline’s expected cost. Try possible values from 10 to 30 in increments of 5. Use <code>expand_grid()</code> to lay out every combination of overbooking level and simulation, <code>case_when()</code> to assign the cost of each scenario, and <code>group_by()</code> with <code>summarise()</code> to compare the levels.</p></li>
</ol>
<details>
<summary>
Suggested Answer
</summary>
<p><em>Optimal Overbooking Strategy: 18 seats</em></p>
<p><em>Minimum Expected Cost: $1,633</em></p>
</details>
<ol start="3" type="1">
<li>In August, Bronco Wine Company must decide how many bottles of next year’s vintage wine to order. Each bottle costs the winery <span class="math inline">\(7.50\)</span> and sells for <span class="math inline">\(10\)</span>. After January 1, all unsold bottles will be returned to the supplier for a refund of <span class="math inline">\(2.50\)</span> per bottle. Bronco believes that the number of bottles it can sell by January 1 follows a uniform distribution with a mean of 200, a maximum value of 300, and a minimum value of 100. The maximum number of bottles Bronco’s supplier can provide is uncertain and follows a normal distribution with a mean of 200 and a standard deviation of 50. Once Bronco places an order, the supplier will charge <span class="math inline">\(7.50\)</span> per bottle if they can supply the entire order; otherwise, they will charge <span class="math inline">\(7.25\)</span> per bottle. Bronco wants to use simulation to analyze the resulting profit for various order quantities.</li>
</ol>
<p>Use 10,000 simulations to determine the optimal number of bottles to produce to maximize the winery’s expected profit. Note that this model has two random variables, which simply means two random columns in the same tibble. Create a five number summary to describe the distribution of profits at the optimal number of bottles.</p>
<details>
<summary>
Suggested Answer
</summary>
<p><em>Optimal Production Level: 200</em></p>
<p><em>Expected Profit: ~$334</em></p>
<p><em>Five Number Summary: min:-250 Q1:229 Q2:415 Q3:500 max:547</em></p>
</details>
<ol start="4" type="1">
<li><p>You are considering an investment in the SPY (S&amp;P 500 ETF) over a 20-year period. Your investment strategy involves making an initial investment, followed by yearly contributions.</p>
<p>The key parameters for your investment are as follows:</p>
<ul>
<li><em>Stock Ticker:</em> SPY (S&amp;P 500 ETF)</li>
<li><em>Initial Investment:</em> $1,000</li>
<li><em>Average Yearly Return:</em> 10% (0.1)</li>
<li><em>Standard Deviation of Yearly Returns:</em> 18% (0.18)</li>
<li><em>Yearly Investment:</em> $6,000</li>
<li><em>Investment Period:</em> 20 years</li>
</ul>
<p>Run 10,000 simulations of your investment over 20 years. Each year, returns are normally distributed with the given average and standard deviation. Track the value of your investment at the end of each year. This model is path dependent, so build a tibble with one row per simulation-year, group it by simulation, and use <code>accumulate()</code> inside <code>mutate()</code> to carry the balance forward. Calculate the following statistics for the investment value at the end of 20 years:</p>
<ul>
<li>Average (mean) end value</li>
<li>Worst Case Scenario: Minimum</li>
<li>Bear Case: 25th percentile (Q1)</li>
<li>Base Case: Median (50th percentile)</li>
<li>Bull Case: 75th percentile (Q3)</li>
<li>Best Case Scenario: Maximum</li>
</ul>
<p>Based on your simulation results, how much can you expect to have in your account after 20 years on average? What are the Bear, Base and Bull case predictions?</p></li>
</ol>
<details>
<summary>
Suggested Answer
</summary>
<p><em>Expected End Value after 20 years: $380,000</em></p>
<p><em>Bear Case: $233,000</em></p>
<p><em>Base Case: $332,000</em></p>
<p><em>Bull Case: $476,000</em></p>
</details>
<ol start="5" type="1">
<li>You are tasked with simulating the price of BTC (Bitcoin) over one year using Brownian motion and plotting the result. Brownian motion is a mathematical model used to describe random motion, often applied in finance to simulate stock price movements. In particular, the returns of a stock are described by the following equation: <span class="math inline">\(\text{returns} = (\mu - 0.5 \times \sigma^2) \times dt + \sigma \times \sqrt{dt} \times \epsilon\)</span>; where <span class="math inline">\(\epsilon\)</span> is a random shock drawn from a standard normal distribution, <span class="math inline">\(\mu\)</span> is the expected annual return, <span class="math inline">\(\sigma^2\)</span> is the variance of returns, and <span class="math inline">\(dt = 1/365\)</span>. Assume that the starting Bitcoin price is 50,000 dollars, with an average return of 40% and standard deviation of 100%. Let the path of Bitcoin be given by: <span class="math inline">\(Price=S0*cumprod(1+returns)\)</span>; where <span class="math inline">\(S0\)</span> is the initial price. Generate 1000 price paths using Brownian motion (set seed to 150). Because the price accumulates multiplicatively with no contributions, <code>cumprod()</code> handles the path within each simulation, so a <code>group_by()</code> and <code>mutate()</code> is all that is required. Report the mean, bear (Q1), base (Q2) and bull cases (Q3) of the final prices after 1 year.</li>
</ol>
<details>
<summary>
Suggested Answer
</summary>
<p><em>Expected End Value 1 year (365 days): $48,293</em></p>
<p><em>Bear Case (Q1): $13,642</em></p>
<p><em>Base Case (Q2): $27,306</em></p>
<p><em>Bull Case (Q3): $58,680</em></p>
</details>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-KI" class="csl-entry" role="listitem">
Kwak, Young, and Lisa Ingall. 2007. <span>“Exploring Monte Carlo Simulation Applications for Project Management.”</span>
</div>
<div id="ref-PMS" class="csl-entry" role="listitem">
Winston, Wayne, and Christian Albright. 2019. <em>Practical Management Science</em>. Cengage.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Tools.html" class="pagination-link" aria-label="Tools for Working With Simulation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Tools for Working With Simulation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Tools2.html" class="pagination-link" aria-label="Time Series Tools">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Time Series Tools</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>